### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ghost** [softawaregmbh/vscode-abc#2]
No issue to report, but I wanted to convey my thanks. My first-ever score in abc is a transcription of Telemann's violin sonata TWV 41:G1 from IMSLP, and it was a pleasure to write in vscode with this extension.

Many thanks!

**Comment by rschacherl** [comment]
Hi!
Thanks a lot for your kind words - good to hear, that my extension is in use ;-)
Have fun with abc and VS Code!
